# Generated by Django 6.1 on 2026-08-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='brakes_abs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='power',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='pros_cons_rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='top_speed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='torque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
